### ISSUE TITLE
How can I implement motion in next.js?

### ISSUE THREAD

**Issue by hollynight0** [hollynight127626/ReadersMenu-Next#4]
I add motion to coming_soon modal.
But it doesn't work.

**Comment by webdog12345** [comment]
To add motion, you have to install Framer Motion.
run this command. yarn add framer-motion
Then add motion like this
 <motion.div
          className='relative p-8 bg-[#181818] rounded-lg shadow-lg flex flex-col items-center'
          style={{ border: '1px solid #FFC13B' }}
          initial={{ x: 300, opacity: 0 }}
          animate={{ x: 0, opacity: 1 }}
          exit={{ x: 300, opacity: 0 }}
          transition={{
            type: 'spring',
            stiffness: 260,
            damping: 20,
          }}
        >
          <div className='text-center text-white text-lg mb-2'>Lampapuy Exclusive NFT Marketplace on Solana</div>
          <div className='text-4xl font-bold bg-gradient-to-r from-yellow-400 via-orange-500 to-orange-600 text-transparent 
          bg-clip-text'>COMING SOON</div>
</motion.div>
